// Dữ liệu sản phẩm từ bảng giá 2025
const products = [
  {
    "stt": 1,
    "tenSanPham": "Led Trụ Nhôm Khối Vinahous 20W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "80.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "64.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "54.400 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 2,
    "tenSanPham": "Led Trụ Nhôm Khối Vinahous 30W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "115.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "92.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "78.200 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 3,
    "tenSanPham": "Led Trụ Nhôm Khối Vinahous 40W",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "150.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "120.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "102.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 4,
    "tenSanPham": "Led Trụ Nhôm Khối Vinahous 50W",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "195.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "156.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "132.600 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 5,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 15W",
    "quyCache": "100b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "45.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "29.520 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 6,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 20W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "60.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "48.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "39.360 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 7,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 30W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "90.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "72.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "59.040 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 8,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 40W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "78.720 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 9,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 50W",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "140.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "112.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "91.840 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 10,
    "tenSanPham": "Led Trụ Nhôm Nhựa Vinasunshin 5W",
    "quyCache": "100b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "21.500 đ",
    "chietKhau": "20%",
    "giaSauCK": "17.200 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "14.104 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 11,
    "tenSanPham": "Led Trụ Nhôm Nhựa Vinasunshin 10W",
    "quyCache": "100b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "26.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "20.800 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "17.056 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 12,
    "tenSanPham": "Led Trụ Nhôm Nhựa Vinasunshin 15W",
    "quyCache": "100b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "31.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "24.800 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "20.336 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 13,
    "tenSanPham": "Led Trụ Nhôm Nhựa Vinasunshin 20W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "39.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "31.200 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "25.584 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 14,
    "tenSanPham": "Led Trụ Nhôm Nhựa Vinasunshin 30W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "47.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "37.600 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "30.832 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 15,
    "tenSanPham": "Led Trụ Nhôm Nhựa Vinasunshin 40W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "69.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "55.200 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "45.264 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 16,
    "tenSanPham": "Led Trụ Nhôm Nhựa Vinasunshin 50W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "89.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "71.200 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "58.384 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 17,
    "tenSanPham": "Led Bán Nguyệt Cao Cấp 1.2m Vinahous 36w",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "190.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "152.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "129.200 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 18,
    "tenSanPham": "Led cà na đỏ",
    "quyCache": "10b/bọc",
    "quyCacheHash": "",
    "dvt": "bọc",
    "giaGoc": "108.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "90.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 19,
    "tenSanPham": "Bộ Led 1,2m 29W Vinahous",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bộ",
    "giaGoc": "125.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "100.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "85.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 20,
    "tenSanPham": "Bóng Led 1,2m T8 29W Vinahous",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "85.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "68.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "57.800 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 21,
    "tenSanPham": "Bộ Led 1,2m 20W Vinahous",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bộ",
    "giaGoc": "97.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "77.600 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "65.960 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 22,
    "tenSanPham": "Bóng Led 1,2m 20W Vinahous",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "62.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "49.600 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "42.160 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 23,
    "tenSanPham": "Búp 3W kính nước đủ màu",
    "quyCache": "10b/bọc",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "",
    "chietKhau": "",
    "giaSauCK": "10.500 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 24,
    "tenSanPham": "Âm Trần Vinahous Viền Trắng 3CĐ 7W",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "85.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "68.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "62.560 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 25,
    "tenSanPham": "Âm Trần Vinahous Viền Vàng 3CĐ 7W",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "85.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "68.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "62.560 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 26,
    "tenSanPham": "Âm Trần Vinahous Cong Viền Trắng 3CĐ 7W",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "95.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "76.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "69.920 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 27,
    "tenSanPham": "Âm Trần Vinahous Cong Viền Vàng 3CĐ 7W",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "95.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "76.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "69.920 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 28,
    "tenSanPham": "Âm Trần Vinahous Liền Khối 7W",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "115.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "92.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "84.640 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 29,
    "tenSanPham": "Âm Trần Vinahous Viền Trắng 3CĐ 9W",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "88.320 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 30,
    "tenSanPham": "Âm Trần Vinahous Viền Vàng 3CĐ 9W",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "88.320 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 31,
    "tenSanPham": "Âm Trần Vinahous Cong Viền Trắng 3CĐ 9W",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "130.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "104.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "95.680 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 32,
    "tenSanPham": "Âm Trần Vinahous Cong Viền Vàng 3CĐ 9W",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "130.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "104.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "95.680 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 33,
    "tenSanPham": "Năng Lượng Mặt Trời VH11 100w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.050.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "840.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "756.000 đ",
    "hetHang": false,
    "icon": "☀️"
  },
  {
    "stt": 34,
    "tenSanPham": "Năng Lượng Mặt Trời VH11 200w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.295.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.036.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "932.400 đ",
    "hetHang": false,
    "icon": "☀️"
  },
  {
    "stt": 35,
    "tenSanPham": "Năng Lượng Mặt Trời VH11 300w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.695.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.356.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.220.400 đ",
    "hetHang": false,
    "icon": "☀️"
  },
  {
    "stt": 36,
    "tenSanPham": "Năng Lượng Mặt Trời VH11 400w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "2.020.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.616.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.454.400 đ",
    "hetHang": false,
    "icon": "☀️"
  },
  {
    "stt": 37,
    "tenSanPham": "Năng Lượng Mặt Trời VH13 100w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.245.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "996.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "896.400 đ",
    "hetHang": false,
    "icon": "☀️"
  },
  {
    "stt": 38,
    "tenSanPham": "Năng Lượng Mặt Trời VH13 200w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.535.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.228.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.105.200 đ",
    "hetHang": false,
    "icon": "☀️"
  },
  {
    "stt": 39,
    "tenSanPham": "Năng Lượng Mặt Trời VH13 300w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.870.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.496.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.346.400 đ",
    "hetHang": false,
    "icon": "☀️"
  },
  {
    "stt": 40,
    "tenSanPham": "Năng Lượng Mặt Trời VH13 400w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "2.250.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.800.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.620.000 đ",
    "hetHang": false,
    "icon": "☀️"
  },
  {
    "stt": 41,
    "tenSanPham": "Năng Lượng MT Đèn Đường Liền Thể VH16 200w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "785.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "628.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "565.200 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 42,
    "tenSanPham": "Năng Lượng MT Đèn Đường Liên Thể VH16 300w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "980.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "784.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "705.600 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 43,
    "tenSanPham": "Năng Lượng MT Đèn Đường Liên Thể VH16 400w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.180.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "944.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "849.600 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 44,
    "tenSanPham": "Năng Lượng MT Đèn Đường Liền Thể VH16 500w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.295.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.036.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "932.400 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 45,
    "tenSanPham": "Năng Lượng Mặt Trời Đèn Đường VH15 300w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.950.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.560.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.404.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 46,
    "tenSanPham": "Năng Lượng Mặt Trời Đèn Đường VH15 400w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "2.228.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.782.400 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.604.160 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 47,
    "tenSanPham": "Năng Lượng Mặt Trời Đèn Đường VH17 200w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.950.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.560.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.404.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 48,
    "tenSanPham": "Năng Lượng Mặt Trời Đèn Đường VH17 300w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "2.250.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.800.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.620.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 49,
    "tenSanPham": "Năng Lượng Mặt Trời Đèn Đường VH17 400w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "2.350.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.880.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.692.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 50,
    "tenSanPham": "Năng Lượng Mặt Trời Đèn Đường VH18 200w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "1.950.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.560.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.404.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 51,
    "tenSanPham": "Năng Lượng Mặt Trời Đèn Đường VH18 300w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "2.250.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.800.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.620.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 52,
    "tenSanPham": "Năng Lượng Mặt Trời Đèn Đường VH18 400w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "2.350.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "1.880.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "1.692.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 53,
    "tenSanPham": "Năng Lượng Mặt Trời Đèn Đường VH18 600w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "3.600.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "2.880.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "2.592.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 54,
    "tenSanPham": "Đèn Pha Điện Vinahous 30w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "175.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "140.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "126.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 55,
    "tenSanPham": "Đèn Pha Điện Vinahous 50w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "210.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "168.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "151.200 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 56,
    "tenSanPham": "Đèn Pha Điện Vinahous 100w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "450.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "360.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "324.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 57,
    "tenSanPham": "Đèn đội 9818",
    "quyCache": "1c/1 hộp",
    "quyCacheHash": "2 ánh sáng Trắng và Vàng",
    "dvt": "cây",
    "giaGoc": "",
    "chietKhau": "",
    "giaSauCK": "87.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 58,
    "tenSanPham": "Led Pha Điện Cao Cấp Vinahous 30w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "380.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "304.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "273.600 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 59,
    "tenSanPham": "Led Pha Điện Cao Cấp Vinahous 50w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "475.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "380.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "342.000 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 60,
    "tenSanPham": "Led Pha Điện Cao Cấp Vinahous 100w",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "795.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "636.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "572.400 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 61,
    "tenSanPham": "Bộ Chống Giật Vinahous 32A",
    "quyCache": "20c/thùng",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "350.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "262.500 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "223.125 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 62,
    "tenSanPham": "Bộ Chống Giật Vinahous 40A",
    "quyCache": "20c/thùng",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "350.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "262.500 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "223.125 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 63,
    "tenSanPham": "Bộ Chống Giật Vinahous 50A",
    "quyCache": "20c/thùng",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "370.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "277.500 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "235.875 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 64,
    "tenSanPham": "Bộ Chống Giật Vinahous 63A",
    "quyCache": "20c/thùng",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "370.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "277.500 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "235.875 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 65,
    "tenSanPham": "Bộ Chống Giật Vinasunshin",
    "quyCache": "20c/thùng",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "190.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "152.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "136.800 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 66,
    "tenSanPham": "CB Cóc Đen Vinahous 15A",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "48.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "30.600 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 67,
    "tenSanPham": "CB Cóc Đen Vinahous 20A",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "48.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "30.600 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 68,
    "tenSanPham": "CB Cóc Đen Vinahous 30A",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "48.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "30.600 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 69,
    "tenSanPham": "CB Cóc Đen Vinahous 40A",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "48.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "30.600 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 70,
    "tenSanPham": "Đuôi Cảm Ứng Người Vinahous",
    "quyCache": "20c/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "113.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "90.400 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "75.333 đ",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 71,
    "tenSanPham": "Đuôi treo trắng Vinahous (không dây)",
    "quyCache": "10b/bọc",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "",
    "chietKhau": "",
    "giaSauCK": "3.200 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 72,
    "tenSanPham": "Đuôi kín nước trắng Vinahous",
    "quyCache": "100c/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "8.900 đ",
    "chietKhau": "15%",
    "giaSauCK": "7.500 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 73,
    "tenSanPham": "Đuôi kín nước đen Vinahous",
    "quyCache": "100c/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "8.500 đ",
    "chietKhau": "15%",
    "giaSauCK": "7.200 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 74,
    "tenSanPham": "Đuôi kín nước trắng Vinashin",
    "quyCache": "100c/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "7.000 đ",
    "chietKhau": "",
    "giaSauCK": "7.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 75,
    "tenSanPham": "Đuôi kín nước đen Vinashin",
    "quyCache": "100c/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "6.700 đ",
    "chietKhau": "",
    "giaSauCK": "6.700 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 76,
    "tenSanPham": "Phích chịu tải 6000W Vinahous",
    "quyCache": "10c/bọc",
    "quyCacheHash": "3 màu Trắng, Vàng, Xanh",
    "dvt": "Cái",
    "giaGoc": "10.500 đ",
    "chietKhau": "20%",
    "giaSauCK": "8.400 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "7.560 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 77,
    "tenSanPham": "Phích âm Vinahous 6000W",
    "quyCache": "10c/bọc",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "12.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "9.600 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "8.640 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 78,
    "tenSanPham": "Phích cắm 4ly Vinahous",
    "quyCache": "10c/bọc",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "4.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "3.200 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 79,
    "tenSanPham": "Đuôi đa năng Vinahous",
    "quyCache": "50c/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "7.800 đ",
    "chietKhau": "20%",
    "giaSauCK": "5.400 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 80,
    "tenSanPham": "Hộp CB cóc",
    "quyCache": "10c/bọc",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "6.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "4.300 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "3.583 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 81,
    "tenSanPham": "Hộp chống giật 2 tép",
    "quyCache": "10c/bọc",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "20.000 đ",
    "chietKhau": "",
    "giaSauCK": "20.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "18.182 đ",
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 82,
    "tenSanPham": "Ổ dài 2CT 4 lỗ 3m Vinahous",
    "quyCache": "20ổ/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "82.000 đ",
    "chietKhau": "",
    "giaSauCK": "82.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "74.545 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 83,
    "tenSanPham": "Ổ dài 2CT 4 lỗ 5m Vinahous",
    "quyCache": "20ổ/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "110.000 đ",
    "chietKhau": "",
    "giaSauCK": "110.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "100.000 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 84,
    "tenSanPham": "Ổ dài 4CT 4 lỗ 3m Vinahous",
    "quyCache": "20ổ/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "117.000 đ",
    "chietKhau": "",
    "giaSauCK": "117.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "106.364 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 85,
    "tenSanPham": "Ổ dài 4CT 4 lỗ 5m Vinahous",
    "quyCache": "20ổ/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "132.000 đ",
    "chietKhau": "",
    "giaSauCK": "132.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "120.000 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 86,
    "tenSanPham": "Ổ dài 4 lỗ sứ không dây Vinahous",
    "quyCache": "20ổ/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "65.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "52.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "47.273 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 87,
    "tenSanPham": "Ổ 3 lỗ DX03 Vinahous",
    "quyCache": "12ổ/lốc",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "22.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "17.600 đ",
    "khuyenMai": "12 tặng 2",
    "giaHoaGia": "15.086 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 88,
    "tenSanPham": "Ổ quay Vinahous 5m",
    "quyCache": "20ổ/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "60.000 đ",
    "chietKhau": "",
    "giaSauCK": "60.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "54.545 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 89,
    "tenSanPham": "Ổ quay Vinahous 8m",
    "quyCache": "20ổ/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "75.000 đ",
    "chietKhau": "",
    "giaSauCK": "75.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "68.182 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 90,
    "tenSanPham": "Ổ quay Vinahous 10m",
    "quyCache": "20ổ/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "82.000 đ",
    "chietKhau": "",
    "giaSauCK": "82.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "74.545 đ",
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 91,
    "tenSanPham": "Đá cắt sắt Xanh Vinahous 1T",
    "quyCache": "100v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "4.200 đ",
    "chietKhau": "20%",
    "giaSauCK": "3.400 đ",
    "khuyenMai": "12%",
    "giaHoaGia": "2.992 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 92,
    "tenSanPham": "Đá cắt sắt Cam lưới Vinahous 1T",
    "quyCache": "100v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "5.200 đ",
    "chietKhau": "20%",
    "giaSauCK": "4.200 đ",
    "khuyenMai": "12%",
    "giaHoaGia": "3.696 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 93,
    "tenSanPham": "Đá Cắt Sắt Xanh Vinashin 1T",
    "quyCache": "100v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "3.400 đ",
    "chietKhau": "20%",
    "giaSauCK": "2.700 đ",
    "khuyenmai": "10%",
    "giaHoaGia": "2.430 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 94,
    "tenSanPham": "Đá mài sắt xanh Vinahous 1T",
    "quyCache": "25v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "8.900 đ",
    "chietKhau": "20%",
    "giaSauCK": "7.200 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "6.480 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 95,
    "tenSanPham": "Đá Cắt Sắt Xanh Vinahous 1.2T",
    "quyCache": "50v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "8.200 đ",
    "chietKhau": "20%",
    "giaSauCK": "6.600 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "6.270 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 96,
    "tenSanPham": "Đá cắt sắt Xanh Vinahous 3,5T",
    "quyCache": "30v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "43.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "34.000 đ",
    "khuyenMai": "12%",
    "giaHoaGia": "29.920 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 97,
    "tenSanPham": "Đá cắt sắt Xanh Vinahous 3T",
    "quyCache": "30v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "37.500 đ",
    "chietKhau": "20%",
    "giaSauCK": "32.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "28.800 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 98,
    "tenSanPham": "Đá cắt sắt Cam lưới Vinahous 3,5T",
    "quyCache": "25v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "52.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "41.600 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "37.440 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 99,
    "tenSanPham": "Nhám xếp Vinahous 40A",
    "quyCache": "30c/thùng",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "95.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "76.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "68.400 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 100,
    "tenSanPham": "Nhám xếp Vinahous 60A",
    "quyCache": "30c/thùng",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "95.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "76.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "68.400 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 101,
    "tenSanPham": "Nhám xếp Vinahous 80A",
    "quyCache": "30c/thùng",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "95.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "76.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "68.400 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 102,
    "tenSanPham": "Nhám xếp Vinahous 120A",
    "quyCache": "30c/thùng",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "95.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "76.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "68.400 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 103,
    "tenSanPham": "Đá cắt gạch chống rung Xanh viền trắng Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "115.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "103.500 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "86.250 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 104,
    "tenSanPham": "Đá cắt gạch chống rung lưới Đỏ Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "110.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "99.000 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "82.500 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 105,
    "tenSanPham": "Đá cắt gạch Xanh lá viền Vàng Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "90.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "81.000 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "67.500 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 106,
    "tenSanPham": "Đá cắt gạch lưới Xanh dương Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "85.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "76.500 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "63.750 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 107,
    "tenSanPham": "Đá cắt gạch đa năng 1T Rồng Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "78.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "70.200 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "58.500 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 108,
    "tenSanPham": "Đá cắt gạch chống rung lưới 1,2T Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "125.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "112.500 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "93.750 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 109,
    "tenSanPham": "Đá cắt gạch Rồng 1,2T",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "",
    "chietKhau": "",
    "giaSauCK": "67.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 110,
    "tenSanPham": "Lưỡi cắt gỗ phi 105x30T Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "60.000 đ",
    "chietKhau": "7%",
    "giaSauCK": "55.800 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "46.500 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 111,
    "tenSanPham": "Bát mài 100x5mm Đỏ Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "55.000 đ",
    "chietKhau": "5%",
    "giaSauCK": "52.250 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "43.542 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 112,
    "tenSanPham": "Bát mài 100x7mm Xanh lá Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "62.000 đ",
    "chietKhau": "5%",
    "giaSauCK": "58.900 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "49.083 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 113,
    "tenSanPham": "Đầu bắn bake Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "vĩ",
    "giaGoc": "78.000 đ",
    "chietKhau": "",
    "giaSauCK": "78.000 đ",
    "khuyenMai": "6 tặng 1",
    "giaHoaGia": "66.857 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 114,
    "tenSanPham": "Đầu bắn bake Hít Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "vĩ",
    "giaGoc": "107.000 đ",
    "chietKhau": "",
    "giaSauCK": "107.000 đ",
    "khuyenMai": "6 tặng 1",
    "giaHoaGia": "91.714 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 115,
    "tenSanPham": "Đầu bắn tole Vinahous",
    "quyCache": "10v/hộp",
    "quyCacheHash": "",
    "dvt": "vĩ",
    "giaGoc": "189.000 đ",
    "chietKhau": "",
    "giaSauCK": "189.000 đ",
    "khuyenMai": "4 tặng 1",
    "giaHoaGia": "151.200 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 116,
    "tenSanPham": "Khoan đa năng 6mm Vinahous",
    "quyCache": "100m/hộp",
    "quyCacheHash": "10 mũi/vĩ",
    "dvt": "mũi",
    "giaGoc": "20.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "18.000 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "17.100 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 117,
    "tenSanPham": "Khoan đa năng 8mm Vinahous",
    "quyCache": "100m/hộp",
    "quyCacheHash": "10 mũi/vĩ",
    "dvt": "mũi",
    "giaGoc": "25.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "23.000 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "21.850 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 118,
    "tenSanPham": "Khoan đa năng 10mm Vinahous",
    "quyCache": "50m/hộp",
    "quyCacheHash": "10 mũi/vĩ",
    "dvt": "mũi",
    "giaGoc": "29.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "26.000 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "24.700 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 119,
    "tenSanPham": "Khoan đa năng 12mm Vinahous",
    "quyCache": "50m/hộp",
    "quyCacheHash": "10 mũi/vĩ",
    "dvt": "mũi",
    "giaGoc": "39.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "37.000 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "35.150 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 120,
    "tenSanPham": "Cây cưa lưỡi trắng Vinahous cao cấp",
    "quyCache": "6c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "225.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "180.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 121,
    "tenSanPham": "Cây Cưa Thép Taiwan Vinahous",
    "quyCache": "6c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "190.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "152.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 122,
    "tenSanPham": "Lưỡi cưa cành Vinahous cao cấp",
    "quyCache": "15c/hộp",
    "quyCacheHash": "",
    "dvt": "chiếc",
    "giaGoc": "157.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "125.600 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 123,
    "tenSanPham": "Lưỡi Cưa Thép Taiwan Vinahous",
    "quyCache": "15c/hộp",
    "quyCacheHash": "",
    "dvt": "chiếc",
    "giaGoc": "156.200 đ",
    "chietKhau": "20%",
    "giaSauCK": "125.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "112.500 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 124,
    "tenSanPham": "Cưa xếp Vinahous",
    "quyCache": "6c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "67.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "53.600 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "48.240 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 125,
    "tenSanPham": "Kéo làm cá Vinahous",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "65.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "55.300 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "50.273 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 126,
    "tenSanPham": "Kéo làm cá Vinahous 2 chức năng",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "80.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "68.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "61.818 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 127,
    "tenSanPham": "Kéo làm cá Vinahous đa chức năng",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "95.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "80.750 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "73.409 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 128,
    "tenSanPham": "Kéo cắt cành Vinahous vân gỗ cao cấp",
    "quyCache": "12c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "182.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "145.600 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 129,
    "tenSanPham": "Kéo cắt cành Vinahous tay bi đỏ cao cấp",
    "quyCache": "12c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "165.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "132.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 130,
    "tenSanPham": "Kéo cắt cành Vinahous trợ lực xám cao cấp",
    "quyCache": "12c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 131,
    "tenSanPham": "Lò xo kéo cắt cành",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "",
    "chietKhau": "",
    "giaSauCK": "2.500 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 132,
    "tenSanPham": "Kìm Điện Vinahous 7in",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "112.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "89.600 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "82.432 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 133,
    "tenSanPham": "Kìm Điện Vinahous 8in",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "88.320 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 134,
    "tenSanPham": "Kìm Cắt Vinahous 6in",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "102.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "81.600 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "75.072 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 135,
    "tenSanPham": "Kìm Nhọn Vinahous 6in",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "102.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "81.600 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "75.072 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 136,
    "tenSanPham": "Kìm Nhọn Vinahous 8in",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "118.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "94.400 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "86.848 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 137,
    "tenSanPham": "Khò Gas Vinahous 923",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "46.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "41.400 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "34.500 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 138,
    "tenSanPham": "Khò Gas Vinahous 928",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "97.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "87.300 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "72.750 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 139,
    "tenSanPham": "Khò Gas Hộp Giấy KG18",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "115.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "103.500 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "86.250 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 140,
    "tenSanPham": "Khò Gas Hộp Giấy KG20",
    "quyCache": "10c/hộp",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "105.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "94.500 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "78.750 đ",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 141,
    "tenSanPham": "Vợt muỗi Nakagami",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "",
    "chietKhau": "",
    "giaSauCK": "87.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 142,
    "tenSanPham": "",
    "quyCache": "",
    "quyCacheHash": "",
    "dvt": "",
    "giaGoc": "",
    "chietKhau": "",
    "giaSauCK": "",
    "khuyenMai": "",
    "giaHoaGia": "",
    "hetHang": false,
    "icon": ""
  }
];

// Hàm gán icon dựa trên tên sản phẩm
function getProductIcon(productName) {
  const name = productName.toLowerCase();
  if (name.includes('led') || name.includes('đèn') || name.includes('bóng')) return '💡';
  if (name.includes('năng lượng')) return '☀️';
  if (name.includes('ổ') || name.includes('phích')) return '🔌';
  if (name.includes('cb') || name.includes('công tắc') || name.includes('chống giật')) return '⚡';
  if (name.includes('đá') || name.includes('lưỡi') || name.includes('kìm') || name.includes('khoan') || name.includes('cưa') || name.includes('kéo')) return '⚙️';
  return '📦';
}

// Gán icon cho các sản phẩm
products.forEach(product => {
  if (product.tenSanPham) {
    product.icon = getProductIcon(product.tenSanPham);
  }
});

// Xuất dữ liệu
export { products };
