// Dữ liệu đầy đủ 142 sản phẩm từ CSV
const products = [
  {
    "stt": 1,
    "tenSanPham": "Led Trụ Nhôm Khối Vinahous 20W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "80.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "64.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "54.400 đ",
    "soLuongTon": 156,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 2,
    "tenSanPham": "Led Trụ Nhôm Khối Vinahous 30W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "115.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "92.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "78.200 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 3,
    "tenSanPham": "Led Trụ Nhôm Khối Vinahous 40W",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "150.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "120.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "102.000 đ",
    "soLuongTon": 142,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 4,
    "tenSanPham": "Led Trụ Nhôm Khối Vinahous 50W",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "195.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "156.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "132.600 đ",
    "soLuongTon": 234,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 5,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 15W",
    "quyCache": "100b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "45.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "29.520 đ",
    "soLuongTon": 178,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 6,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 20W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "60.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "48.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "39.360 đ",
    "soLuongTon": 165,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 7,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 30W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "90.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "72.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "59.040 đ",
    "soLuongTon": 97,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 8,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 40W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "78.720 đ",
    "soLuongTon": 134,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 9,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinahous 50W",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "150.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "120.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "98.400 đ",
    "soLuongTon": 198,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 10,
    "tenSanPham": "Led Trụ Nhôm Khối Vinasunshin 20W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "75.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "60.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "51.000 đ",
    "soLuongTon": 187,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 11,
    "tenSanPham": "Led Trụ Nhôm Khối Vinasunshin 30W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "110.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "88.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "74.800 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 12,
    "tenSanPham": "Led Trụ Nhôm Khối Vinasunshin 40W",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "145.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "116.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "98.600 đ",
    "soLuongTon": 156,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 13,
    "tenSanPham": "Led Trụ Nhôm Khối Vinasunshin 50W",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "190.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "152.000 đ",
    "khuyenMai": "15%",
    "giaHoaGia": "129.200 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 14,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinasunshin 15W",
    "quyCache": "100b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "42.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "33.600 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "27.552 đ",
    "soLuongTon": 167,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 15,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinasunshin 20W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "57.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "45.600 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "37.392 đ",
    "soLuongTon": 201,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 16,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinasunshin 30W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "87.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "69.600 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "57.072 đ",
    "soLuongTon": 134,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 17,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinasunshin 40W",
    "quyCache": "30b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "117.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "93.600 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "76.752 đ",
    "soLuongTon": 178,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 18,
    "tenSanPham": "Led Nhôm Nhựa Cao Cấp Vinasunshin 50W",
    "quyCache": "20b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "147.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "117.600 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "96.432 đ",
    "soLuongTon": 145,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 19,
    "tenSanPham": "Led Bulb Nhôm Nhựa Vinahous 15W",
    "quyCache": "100b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "38.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "30.400 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "24.928 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 20,
    "tenSanPham": "Led Bulb Nhôm Nhựa Vinahous 20W",
    "quyCache": "100b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "48.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "38.400 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "31.488 đ",
    "soLuongTon": 156,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 21,
    "tenSanPham": "Led Bulb Nhôm Nhựa Vinahous 30W",
    "quyCache": "50b/thùng",
    "quyCacheHash": "",
    "dvt": "bóng",
    "giaGoc": "70.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "56.000 đ",
    "khuyenMai": "18%",
    "giaHoaGia": "45.920 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 22,
    "tenSanPham": "Ổ Cắm Điện 3 Chấu Panasonic",
    "quyCache": "10 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "25.000 đ",
    "chietKhau": "",
    "giaSauCK": "25.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "23.000 đ",
    "soLuongTon": 198,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 23,
    "tenSanPham": "Ổ Cắm Điện 2 Chấu Panasonic",
    "quyCache": "10 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "20.000 đ",
    "chietKhau": "",
    "giaSauCK": "20.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "18.400 đ",
    "soLuongTon": 234,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 24,
    "tenSanPham": "Công Tắc Đơn Panasonic",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "18.000 đ",
    "chietKhau": "",
    "giaSauCK": "18.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "16.560 đ",
    "soLuongTon": 167,
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 25,
    "tenSanPham": "Công Tắc Đôi Panasonic",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "28.000 đ",
    "chietKhau": "",
    "giaSauCK": "28.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "25.760 đ",
    "soLuongTon": 145,
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 26,
    "tenSanPham": "Công Tắc Ba Panasonic",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "38.000 đ",
    "chietKhau": "",
    "giaSauCK": "38.000 đ",
    "khuyenMai": "8%",
    "giaHoaGia": "34.960 đ",
    "soLuongTon": 156,
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 27,
    "tenSanPham": "Ổ Cắm Điện 3 Chấu Sino",
    "quyCache": "10 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "18.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "14.400 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "12.960 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 28,
    "tenSanPham": "Ổ Cắm Điện 2 Chấu Sino",
    "quyCache": "10 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "15.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "12.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "10.800 đ",
    "soLuongTon": 212,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 29,
    "tenSanPham": "Công Tắc Đơn Sino",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "12.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "9.600 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "8.640 đ",
    "soLuongTon": 234,
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 30,
    "tenSanPham": "Công Tắc Đôi Sino",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "18.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "14.400 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "12.960 đ",
    "soLuongTon": 178,
    "hetHang": false,
    "icon": "⚡"
  },
  {
    "stt": 31,
    "tenSanPham": "Dây Điện Cadivi 1.5 mm²",
    "quyCache": "100m/cuộn",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "380.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "285.000 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "237.500 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "🔗"
  },
  {
    "stt": 32,
    "tenSanPham": "Dây Điện Cadivi 2.5 mm²",
    "quyCache": "100m/cuộn",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "580.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "435.000 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "362.500 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "🔗"
  },
  {
    "stt": 33,
    "tenSanPham": "Dây Điện Cadivi 4 mm²",
    "quyCache": "100m/cuộn",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "920.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "690.000 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "575.000 đ",
    "soLuongTon": 45,
    "hetHang": false,
    "icon": "🔗"
  },
  {
    "stt": 34,
    "tenSanPham": "Dây Điện Cadivi 6 mm²",
    "quyCache": "100m/cuộn",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "1.350.000 đ",
    "chietKhau": "25%",
    "giaSauCK": "1.012.500 đ",
    "khuyenMai": "10 tặng 2",
    "giaHoaGia": "843.750 đ",
    "soLuongTon": 78,
    "hetHang": false,
    "icon": "🔗"
  },
  {
    "stt": 35,
    "tenSanPham": "Ống Luồn Dây Điện PVC Ø16",
    "quyCache": "100m/cuộn",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "180.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "153.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "139.090 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "🔩"
  },
  {
    "stt": 36,
    "tenSanPham": "Ống Luồn Dây Điện PVC Ø20",
    "quyCache": "100m/cuộn",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "220.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "187.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "170.000 đ",
    "soLuongTon": 98,
    "hetHang": false,
    "icon": "🔩"
  },
  {
    "stt": 37,
    "tenSanPham": "Ống Luồn Dây Điện PVC Ø25",
    "quyCache": "100m/cuộn",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "280.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "238.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "216.364 đ",
    "soLuongTon": 134,
    "hetHang": false,
    "icon": "🔩"
  },
  {
    "stt": 38,
    "tenSanPham": "CB MCB 1P 10A Schneider",
    "quyCache": "12 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "85.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "76.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "72.675 đ",
    "soLuongTon": 145,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 39,
    "tenSanPham": "CB MCB 1P 16A Schneider",
    "quyCache": "12 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "87.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "78.300 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "74.385 đ",
    "soLuongTon": 167,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 40,
    "tenSanPham": "CB MCB 1P 20A Schneider",
    "quyCache": "12 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "89.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "80.100 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "76.095 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 41,
    "tenSanPham": "CB MCB 2P 20A Schneider",
    "quyCache": "6 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "165.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "148.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "141.075 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 42,
    "tenSanPham": "CB MCB 2P 32A Schneider",
    "quyCache": "6 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "185.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "166.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "158.175 đ",
    "soLuongTon": 156,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 43,
    "tenSanPham": "Quạt Trần Panasonic F-56VG",
    "quyCache": "1 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "850.000 đ",
    "chietKhau": "",
    "giaSauCK": "850.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "765.000 đ",
    "soLuongTon": 78,
    "hetHang": false,
    "icon": "🌀"
  },
  {
    "stt": 44,
    "tenSanPham": "Quạt Trần Panasonic F-60VG",
    "quyCache": "1 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "950.000 đ",
    "chietKhau": "",
    "giaSauCK": "950.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "855.000 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "🌀"
  },
  {
    "stt": 45,
    "tenSanPham": "Mũi Khoan Bê Tông Ø6mm",
    "quyCache": "50 mũi/hộp",
    "quyCacheHash": "",
    "dvt": "mũi",
    "giaGoc": "8.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "6.400 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "5.760 đ",
    "soLuongTon": 234,
    "hetHang": false,
    "icon": "🔧"
  },
  {
    "stt": 46,
    "tenSanPham": "Mũi Khoan Bê Tông Ø8mm",
    "quyCache": "50 mũi/hộp",
    "quyCacheHash": "",
    "dvt": "mũi",
    "giaGoc": "10.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "8.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "7.200 đ",
    "soLuongTon": 198,
    "hetHang": false,
    "icon": "🔧"
  },
  {
    "stt": 47,
    "tenSanPham": "Mũi Khoan Bê Tông Ø10mm",
    "quyCache": "50 mũi/hộp",
    "quyCacheHash": "",
    "dvt": "mũi",
    "giaGoc": "12.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "9.600 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "8.640 đ",
    "soLuongTon": 167,
    "hetHang": false,
    "icon": "🔧"
  },
  {
    "stt": 48,
    "tenSanPham": "Mũi Khoan Bê Tông Ø12mm",
    "quyCache": "25 mũi/hộp",
    "quyCacheHash": "",
    "dvt": "mũi",
    "giaGoc": "15.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "12.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "10.800 đ",
    "soLuongTon": 134,
    "hetHang": false,
    "icon": "🔧"
  },
  {
    "stt": 49,
    "tenSanPham": "Ổ Cắm Kéo Dài 3m 3 Lỗ",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "65.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "55.250 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "49.725 đ",
    "soLuongTon": 145,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 50,
    "tenSanPham": "Ổ Cắm Kéo Dài 5m 3 Lỗ",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "85.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "72.250 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "65.025 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 51,
    "tenSanPham": "Ổ Cắm Kéo Dài 10m 3 Lỗ",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "120.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "102.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "91.800 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 52,
    "tenSanPham": "Ổ Cắm Kéo Dài 20m 3 Lỗ",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "200.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "170.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "153.000 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 53,
    "tenSanPham": "Ổ Cắm Kéo Dài 3m 6 Lỗ",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "95.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "80.750 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "72.675 đ",
    "soLuongTon": 156,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 54,
    "tenSanPham": "Ổ Cắm Kéo Dài 5m 6 Lỗ",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "115.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "97.750 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "87.975 đ",
    "soLuongTon": 134,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 55,
    "tenSanPham": "Ổ Cắm Kéo Dài 10m 6 Lỗ",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "150.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "127.500 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "114.750 đ",
    "soLuongTon": 98,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 56,
    "tenSanPham": "Ổ Cắm Kéo Dài 20m 6 Lỗ",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "250.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "212.500 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "191.250 đ",
    "soLuongTon": 76,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 57,
    "tenSanPham": "Ổ Cắm Lioa 3 Lỗ 2m",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "35.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "28.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "25.200 đ",
    "soLuongTon": 178,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 58,
    "tenSanPham": "Ổ Cắm Lioa 6 Lỗ 2m",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "55.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "44.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "39.600 đ",
    "soLuongTon": 145,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 59,
    "tenSanPham": "Ổ Cắm Lioa 3 Lỗ 5m",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "55.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "44.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "39.600 đ",
    "soLuongTon": 167,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 60,
    "tenSanPham": "Ổ Cắm Lioa 6 Lỗ 5m",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "ổ",
    "giaGoc": "75.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "60.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "54.000 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "🔌"
  },
  {
    "stt": 61,
    "tenSanPham": "Led Ốp Trần Tròn 18W Vinahous",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "86.400 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 62,
    "tenSanPham": "Led Ốp Trần Tròn 24W Vinahous",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "150.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "120.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "108.000 đ",
    "soLuongTon": 134,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 63,
    "tenSanPham": "Led Ốp Trần Vuông 18W Vinahous",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "125.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "100.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "90.000 đ",
    "soLuongTon": 156,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 64,
    "tenSanPham": "Led Ốp Trần Vuông 24W Vinahous",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "155.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "124.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "111.600 đ",
    "soLuongTon": 112,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 65,
    "tenSanPham": "Led Downlight 3W Vinahous",
    "quyCache": "50 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "35.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "28.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "25.200 đ",
    "soLuongTon": 234,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 66,
    "tenSanPham": "Led Downlight 5W Vinahous",
    "quyCache": "50 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "45.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "32.400 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 67,
    "tenSanPham": "Led Downlight 7W Vinahous",
    "quyCache": "50 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "55.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "44.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "39.600 đ",
    "soLuongTon": 167,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 68,
    "tenSanPham": "Led Downlight 9W Vinahous",
    "quyCache": "30 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "65.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "52.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "46.800 đ",
    "soLuongTon": 145,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 69,
    "tenSanPham": "Led Downlight 12W Vinahous",
    "quyCache": "30 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "85.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "68.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "61.200 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 70,
    "tenSanPham": "Led Tube T8 0.6m 9W Vinahous",
    "quyCache": "25 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "65.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "52.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "46.800 đ",
    "soLuongTon": 178,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 71,
    "tenSanPham": "Led Tube T8 1.2m 18W Vinahous",
    "quyCache": "25 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "95.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "76.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "68.400 đ",
    "soLuongTon": 156,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 72,
    "tenSanPham": "Led Bộ Máng T8 0.6m 9W",
    "quyCache": "10 bộ/thùng",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "86.400 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 73,
    "tenSanPham": "Led Bộ Máng T8 1.2m 18W",
    "quyCache": "10 bộ/thùng",
    "quyCacheHash": "",
    "dvt": "Bộ",
    "giaGoc": "150.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "120.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "108.000 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 74,
    "tenSanPham": "Đèn Led Pha 10W Vinahous",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "86.400 đ",
    "soLuongTon": 134,
    "hetHang": false,
    "icon": "🏮"
  },
  {
    "stt": 75,
    "tenSanPham": "Đèn Led Pha 20W Vinahous",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "180.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "144.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "129.600 đ",
    "soLuongTon": 112,
    "hetHang": false,
    "icon": "🏮"
  },
  {
    "stt": 76,
    "tenSanPham": "Đèn Led Pha 30W Vinahous",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "250.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "200.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "180.000 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "🏮"
  },
  {
    "stt": 77,
    "tenSanPham": "Đèn Led Pha 50W Vinahous",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "380.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "304.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "273.600 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "🏮"
  },
  {
    "stt": 78,
    "tenSanPham": "Đèn Led Pha 100W Vinahous",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "650.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "520.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "468.000 đ",
    "soLuongTon": 45,
    "hetHang": false,
    "icon": "🏮"
  },
  {
    "stt": 79,
    "tenSanPham": "Đèn Led Nhà Xưởng 50W UFO",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "450.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "360.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "324.000 đ",
    "soLuongTon": 78,
    "hetHang": false,
    "icon": "🏮"
  },
  {
    "stt": 80,
    "tenSanPham": "Đèn Led Nhà Xưởng 100W UFO",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "750.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "600.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "540.000 đ",
    "soLuongTon": 56,
    "hetHang": false,
    "icon": "🏮"
  },
  {
    "stt": 81,
    "tenSanPham": "Đèn Led Nhà Xưởng 150W UFO",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "950.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "760.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "684.000 đ",
    "soLuongTon": 34,
    "hetHang": false,
    "icon": "🏮"
  },
  {
    "stt": 82,
    "tenSanPham": "Đèn Led Nhà Xưởng 200W UFO",
    "quyCache": "2 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "1.200.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "960.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "864.000 đ",
    "soLuongTon": 23,
    "hetHang": false,
    "icon": "🏮"
  },
  {
    "stt": 83,
    "tenSanPham": "Đèn Led Dây 5050 RGB 5m",
    "quyCache": "20 cuộn/thùng",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "85.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "68.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "61.200 đ",
    "soLuongTon": 145,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 84,
    "tenSanPham": "Đèn Led Dây 2835 Trắng 5m",
    "quyCache": "20 cuộn/thùng",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "65.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "52.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "46.800 đ",
    "soLuongTon": 167,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 85,
    "tenSanPham": "Đèn Led Dây 2835 Vàng 5m",
    "quyCache": "20 cuộn/thùng",
    "quyCacheHash": "",
    "dvt": "cây",
    "giaGoc": "65.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "52.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "46.800 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "🔆"
  },
  {
    "stt": 86,
    "tenSanPham": "Nguồn Led 12V 5A 60W",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "86.400 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 87,
    "tenSanPham": "Nguồn Led 12V 10A 120W",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "180.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "144.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "129.600 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 88,
    "tenSanPham": "Nguồn Led 12V 20A 240W",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "320.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "256.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "230.400 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 89,
    "tenSanPham": "Nguồn Led 24V 5A 120W",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "150.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "120.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "108.000 đ",
    "soLuongTon": 112,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 90,
    "tenSanPham": "Nguồn Led 24V 10A 240W",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "280.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "224.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "201.600 đ",
    "soLuongTon": 78,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 91,
    "tenSanPham": "Timer Hẹn Giờ Cơ 24h",
    "quyCache": "50 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "45.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "32.400 đ",
    "soLuongTon": 156,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 92,
    "tenSanPham": "Timer Hẹn Giờ Điện Tử 7 Ngày",
    "quyCache": "30 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "85.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "68.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "61.200 đ",
    "soLuongTon": 134,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 93,
    "tenSanPham": "Cảm Biến Chuyển Động PIR",
    "quyCache": "50 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "65.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "52.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "46.800 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 94,
    "tenSanPham": "Cảm Biến Ánh Sáng Photoswitch",
    "quyCache": "50 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "35.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "28.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "25.200 đ",
    "soLuongTon": 212,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 95,
    "tenSanPham": "Dimmer Điều Chỉnh Độ Sáng 500W",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "95.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "76.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "68.400 đ",
    "soLuongTon": 145,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 96,
    "tenSanPham": "Dimmer Điều Chỉnh Độ Sáng 1000W",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "125.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "100.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "90.000 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 97,
    "tenSanPham": "Băng Keo Điện 3M Super 88",
    "quyCache": "200 cuộn/thùng",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "25.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "20.000 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "18.182 đ",
    "soLuongTon": 345,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 98,
    "tenSanPham": "Băng Keo Điện Tesa PVC",
    "quyCache": "200 cuộn/thùng",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "18.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "14.400 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "13.091 đ",
    "soLuongTon": 289,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 99,
    "tenSanPham": "Băng Keo Điện Đen Thường",
    "quyCache": "200 cuộn/thùng",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "12.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "9.600 đ",
    "khuyenMai": "10 tặng 1",
    "giaHoaGia": "8.727 đ",
    "soLuongTon": 456,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 100,
    "tenSanPham": "Đai Rút Nhựa 3.6x200mm",
    "quyCache": "1000 sợi/bọc",
    "quyCacheHash": "",
    "dvt": "bọc",
    "giaGoc": "85.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "68.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "61.200 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 101,
    "tenSanPham": "Đai Rút Nhựa 4.8x300mm",
    "quyCache": "1000 sợi/bọc",
    "quyCacheHash": "",
    "dvt": "bọc",
    "giaGoc": "120.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "96.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "86.400 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 102,
    "tenSanPham": "Kẹp Nối Dây Điện 2.5mm²",
    "quyCache": "100 cái/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "5.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "4.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "3.600 đ",
    "soLuongTon": 567,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 103,
    "tenSanPham": "Kẹp Nối Dây Điện 4mm²",
    "quyCache": "100 cái/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "8.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "6.400 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "5.760 đ",
    "soLuongTon": 434,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 104,
    "tenSanPham": "Kẹp Nối Dây Điện 6mm²",
    "quyCache": "100 cái/hộp",
    "quyCacheHash": "",
    "dvt": "viên",
    "giaGoc": "12.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "9.600 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "8.640 đ",
    "soLuongTon": 312,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 105,
    "tenSanPham": "Remote Điều Khiển Led RGB",
    "quyCache": "50 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "25.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "20.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "18.000 đ",
    "soLuongTon": 234,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 106,
    "tenSanPham": "Controller Led RGB 12V",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "45.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "32.400 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 107,
    "tenSanPham": "Contactor 3P 25A Schneider",
    "quyCache": "10 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "285.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "256.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "243.675 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 108,
    "tenSanPham": "Contactor 3P 40A Schneider",
    "quyCache": "10 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "385.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "346.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "329.175 đ",
    "soLuongTon": 45,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 109,
    "tenSanPham": "Contactor 3P 65A Schneider",
    "quyCache": "5 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "485.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "436.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "414.675 đ",
    "soLuongTon": 34,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 110,
    "tenSanPham": "Relay Trung Gian 8 Chân",
    "quyCache": "50 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "35.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "28.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "25.200 đ",
    "soLuongTon": 234,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 111,
    "tenSanPham": "Relay Trung Gian 11 Chân",
    "quyCache": "50 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "45.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "32.400 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 112,
    "tenSanPham": "Socket Relay 8 Chân",
    "quyCache": "50 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "15.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "12.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "10.800 đ",
    "soLuongTon": 345,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 113,
    "tenSanPham": "Socket Relay 11 Chân",
    "quyCache": "50 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "18.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "14.400 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "12.960 đ",
    "soLuongTon": 289,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 114,
    "tenSanPham": "Tủ Điện Nhựa 4 Nhánh Schneider",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "65.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "55.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "52.488 đ",
    "soLuongTon": 134,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 115,
    "tenSanPham": "Tủ Điện Nhựa 6 Nhánh Schneider",
    "quyCache": "20 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "85.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "72.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "68.638 đ",
    "soLuongTon": 112,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 116,
    "tenSanPham": "Tủ Điện Nhựa 8 Nhánh Schneider",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "105.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "89.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "84.788 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 117,
    "tenSanPham": "Tủ Điện Nhựa 12 Nhánh Schneider",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "135.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "114.750 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "109.013 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 118,
    "tenSanPham": "Tủ Điện Sắt 20x30cm",
    "quyCache": "10 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "185.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "157.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "149.388 đ",
    "soLuongTon": 78,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 119,
    "tenSanPham": "Tủ Điện Sắt 30x40cm",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "285.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "242.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "230.138 đ",
    "soLuongTon": 56,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 120,
    "tenSanPham": "Tủ Điện Sắt 40x50cm",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "385.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "327.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "310.888 đ",
    "soLuongTon": 45,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 121,
    "tenSanPham": "Cầu Dao 2P 63A",
    "quyCache": "10 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "125.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "106.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "100.938 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 122,
    "tenSanPham": "Cầu Dao 2P 100A",
    "quyCache": "5 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "185.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "157.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "149.388 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 123,
    "tenSanPham": "Cầu Dao 3P 63A",
    "quyCache": "5 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "165.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "140.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "133.238 đ",
    "soLuongTon": 78,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 124,
    "tenSanPham": "Cầu Dao 3P 100A",
    "quyCache": "5 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "245.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "208.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "197.838 đ",
    "soLuongTon": 56,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 125,
    "tenSanPham": "Áp Tô Mát 2P 63A",
    "quyCache": "5 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "165.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "140.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "133.238 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 126,
    "tenSanPham": "Áp Tô Mát 3P 63A",
    "quyCache": "5 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "225.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "191.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "181.688 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 127,
    "tenSanPham": "Khởi Động Từ 3P 18A",
    "quyCache": "10 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "185.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "166.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "158.175 đ",
    "soLuongTon": 78,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 128,
    "tenSanPham": "Khởi Động Từ 3P 32A",
    "quyCache": "5 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "285.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "256.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "243.675 đ",
    "soLuongTon": 56,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 129,
    "tenSanPham": "Rơ Le Nhiệt 12-18A",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "85.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "76.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "72.675 đ",
    "soLuongTon": 123,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 130,
    "tenSanPham": "Rơ Le Nhiệt 23-32A",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "125.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "112.500 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "106.875 đ",
    "soLuongTon": 89,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 131,
    "tenSanPham": "Nút Nhấn Đỏ NO 22mm",
    "quyCache": "50 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "25.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "20.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "18.000 đ",
    "soLuongTon": 234,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 132,
    "tenSanPham": "Nút Nhấn Xanh NO 22mm",
    "quyCache": "50 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "25.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "20.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "18.000 đ",
    "soLuongTon": 189,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 133,
    "tenSanPham": "Nút Nhấn Khẩn Cấp 40mm",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "45.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "36.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "32.400 đ",
    "soLuongTon": 167,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 134,
    "tenSanPham": "Đèn Báo LED 22mm Đỏ",
    "quyCache": "50 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "35.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "28.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "25.200 đ",
    "soLuongTon": 212,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 135,
    "tenSanPham": "Đèn Báo LED 22mm Xanh",
    "quyCache": "50 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "35.000 đ",
    "chietKhau": "20%",
    "giaSauCK": "28.000 đ",
    "khuyenMai": "10%",
    "giaHoaGia": "25.200 đ",
    "soLuongTon": 198,
    "hetHang": false,
    "icon": "💡"
  },
  {
    "stt": 136,
    "tenSanPham": "Đồng Hồ Đo Điện Áp AC 0-500V",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "125.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "106.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "100.938 đ",
    "soLuongTon": 67,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 137,
    "tenSanPham": "Đồng Hồ Đo Dòng Điện AC 0-100A",
    "quyCache": "20 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "135.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "114.750 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "109.013 đ",
    "soLuongTon": 78,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 138,
    "tenSanPham": "Ampe Kìm Đo AC/DC Fluke",
    "quyCache": "5 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "1.250.000 đ",
    "chietKhau": "7%",
    "giaSauCK": "1.162.500 đ",
    "khuyenMai": "",
    "giaHoaGia": "1.162.500 đ",
    "soLuongTon": 23,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 139,
    "tenSanPham": "Đồng Hồ Vạn Năng Digital",
    "quyCache": "10 cái/hộp",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "185.000 đ",
    "chietKhau": "15%",
    "giaSauCK": "157.250 đ",
    "khuyenMai": "5%",
    "giaHoaGia": "149.388 đ",
    "soLuongTon": 45,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 140,
    "tenSanPham": "Máy Hàn Que WELD 200A",
    "quyCache": "2 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "2.850.000 đ",
    "chietKhau": "5%",
    "giaSauCK": "2.707.500 đ",
    "khuyenMai": "",
    "giaHoaGia": "2.707.500 đ",
    "soLuongTon": 12,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 141,
    "tenSanPham": "Máy Cắt Plasma 40A",
    "quyCache": "1 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "3.850.000 đ",
    "chietKhau": "5%",
    "giaSauCK": "3.657.500 đ",
    "khuyenMai": "",
    "giaHoaGia": "3.657.500 đ",
    "soLuongTon": 8,
    "hetHang": false,
    "icon": "⚙️"
  },
  {
    "stt": 142,
    "tenSanPham": "Máy Khoan Động Lực Bosch 26mm",
    "quyCache": "5 cái/thùng",
    "quyCacheHash": "",
    "dvt": "Cái",
    "giaGoc": "1.950.000 đ",
    "chietKhau": "10%",
    "giaSauCK": "1.755.000 đ",
    "khuyenMai": "",
    "giaHoaGia": "1.755.000 đ",
    "soLuongTon": 15,
    "hetHang": false,
    "icon": "🔧"
  }
];

module.exports = products;
